name: pub-dry-run

on:
  pull_request:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

defaults:
  run:
    working-directory: "."

jobs:
  dry-run:
    name: dry-run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - run: dart pub publish --dry-run
